### ISSUE TITLE
AsyncHttpxClientWrapper has no attribute '_state' in v0.28.0

### ISSUE THREAD

**Issue by vintagedave** [encode/httpx#3431]
Hello. When I upgrade HTTPX from 0.27.0 to 0.28.0, I get the following error. I do not get a call stack, and I'm not expert enough on Python to know why (usually I would get one.)

This is likely being called by the openai library, which is version 1.50.2.

```
 File "/opt/venv/lib/python3.11/site-packages/httpx/_client.py", line 1984, in aclose

    if self._state != ClientState.CLOSED:

       ^^^^^^^^^^^

AttributeError: 'AsyncHttpxClientWrapper' object has no attribute '_state'
```

**Comment by vfazio** [comment]
you'll want to bump to at least https://github.com/openai/openai-python/releases/tag/v1.55.3 I think. older versions will not work will with httpx 0.28.0. you could optionally pin your httpx dependency to an older version.
